### PR TITLE
Forge 1.12.2 PLEASE READ

### PR DESCRIPTION
**Pull request by CorvetteCole**
Hello, I've ported the changes made in version 1.5 of this mod to Minecraft Forge 1.12.2. It is a nice improvement. I cannot make a branch on your remote, but you can merge this pull request in to a separate version/1.12 branch which would be nice. I will be maintaining this and keeping it up to date with the main mod changes until I stop using 1.12 on my server.

Thanks!

### CODE REVIEW

**Comment by marchermans** [comment]
Wrong target branch
And 1.12 is depreciated and out of support.
Sorry.

**Comment by CorvetteCole** [comment]
hello, I would like to maintain support for 1.12 all on my own for this project. Also, github wouldn't let me select a new branch as a target so I was hoping you would be able to change the target branch to version/1.12

**Comment by someaddons** [comment]
as Orion said we no longer support that outdated version at all. Also your effort is kinda useless, dynamic view does have a 1.12 released already

**Comment by CorvetteCole** [comment]
@someaddons the point of this port was to bring the better tick averaging from version 1.5 of this mod to 1.12, because that was causing lag spikes on my server (something related to disk scheduling with the CPU). This port has completely fixed those issues. I will regardless maintain my fork of this, but it is a significant improvement which is why I made this PR

**Comment by someaddons** [comment]
better tick averaging only does slightly reduce the amount of actions it takes, those will be just as laggy/not laggy when they do happen

**Comment by CorvetteCole** [comment]
I'm not trying to argue. This change made a big difference to server performance because previously lag spikes due to auto saving could trigger cascading lag from this loading or unloading chunks. I understand not merging it, so I will just maintain it separately in my own fork

**Pull request closed without merging**
